### ISSUE TITLE
ISseeker.cfg has hard-coded paths

### ISSUE THREAD

**Issue by tseemann** [JCVI-VIRIFX/ISseeker#2]
Can you make the default config look for just "blast" so that it finds it wherever we have it in the PATH ?

Instead of /usr/local/bin ?

**Comment by bishbrian** [comment]
I generally don't like using whatever commands are found in a user's path, because then two users may see different results for the same inputs, or the app may appear broken because of an incompatible version of a support application in one user's path versus another's.

**Comment by tseemann** [comment]
I think you have made the wrong decision.   This will affect usage of your software.  Most people use tools installed system-wide on clusters etc. And when they install it themselves, they still depend on the standard tools like BLAST etc being installed globally.  Every frustrated user is one citation you probably won't get. But it's your call.
